# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = 'https://wutaner.com'

# Basic metadata configuration for your blog.
title = "wutaner's blog"
copyright = 'Copyright © 2024 wutaner'
# languageCode = 'en-us' # Removed, defined in [languages]

# Set default language
defaultContentLanguage = "en"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

# Languages Configuration
[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 1

  [languages.zh-cn]
    languageCode = "zh-CN"
    languageName = "简体中文"
    weight = 2


[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

# Global parameters (apply to all languages unless overridden)
[params]
  # --- Site Metadata ---
  description = 'wutaner'
  author = 'wutaner'
  authorlink = 'https://wutaner.com/'
  email = "sjk131@outlook.com"
  favicon = 'https://wutaner.com/favicon.ico'
  images = ["images/share.png"] # For social sharing
  title = "wutaner's blog" # For OpenGraph site_name

  # --- Theme Settings ---
  hideMadeWithLine = false
  dateFormat = "2006-01-02"

  # --- Feature Flags ---
  enableUpvote = true
  workerUrl = 'https://blog-upvote.sjk131.workers.dev'

[markup]
  [markup.highlight]
    noClasses = false