baseURL = 'https://ezyang.github.io/ai-blindspots/'
languageCode = 'en-us'
title = 'AI Blindspots'
theme = 'hugo-bearblog'

enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Blindspots in LLMs I've noticed while AI coding. Sonnet family emphasis."
  title = "AI Blindspots"
  dateFormat = "2006-01-02"
  hideMadeWithLine = true

[markup.goldmark.renderer]
  unsafe = true
